# -*- coding: utf-8 -*-
"""Algorithm to calculate change for purchases and deliver accurate cash notes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R8CujLb1SiORbrahTt3JjwruMskmJeof
"""

#Algorithm to calculate change for purchases and deliver accurate cash notes

compra = float(input("Digite o valor da compra: "))
dado = float(input("Digite o valor dado: "))
troco = round(dado - compra, 2)
print(f"O troco é:",troco)

while troco >= 0.05:
    if 50 <= troco < 100:
        troco -= 50;
        print("1 Nota de 50")
    elif 100 <= troco:
        troco -=100;
        print("1 Nota de 100")
    elif 20 <= troco < 50:
        troco -= 20
        print("1 Nota de 20")
    elif 10 <= troco < 20:
        troco -= 10
        print("1 Nota de 10")
    elif 5 <= troco < 10:
        troco -= 5
        print("1 Nota de 5")
    elif 2 <= troco < 5:
        troco -= 2
        print("1 Nota de 2")
    elif 1 <= troco < 2:
        troco -= 1
        print("1 Nota de 1")
    elif 0.50 <= troco < 1:
        troco -= 0.50
        print("1 moeda de 0,50")
    elif 0.10 <= troco < 0.50:
        troco -= 0.10
        print("1 Moeda de 0.10")
    elif 0.05 <= troco < 0.10:
        troco -= 0.05
        print("1 Moeda de 0.05")