# -*- coding: utf-8 -*-
"""Course Activities.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wr5vjuUxA6y0zXlV5ocN3DnT-JWoR1qk
"""

#Atividade em Desenvolvimento de sistemas:

#1: Dada a lista L = [5, 7, 2, 9, 4, 1, 3], escreva um programa que imprima as seguintes informações:
#Tamanho da lista
lista = [5,7,2,9,4,1,3]
print("O tamanho da lista é:",len(lista))
#Maior valor da lista:
print("O maior número da lista é:",max(lista))
#Menor valor da lista:
print("O menos número da lista é:",min(lista))
#Soma de todos os valores da lista:
print("A soma de todos os números da lista é:",sum(lista))
#Ordenação em ordem crescente:
print("A lista ordenada é",sorted(lista))
#Ordenação em ordem decrescente:
print("A lista ordenada é",sorted(lista, reverse = True))

#Faça um programa que leia 4 valores, calcule a média e imprima positivo ou negativo (para ser posi-
#tivo a média deve ser acima de 1).
a = float(input("Digite o primeiro número: "))
b = float(input("Digite o segundo número: "))
c = float(input("Digite o terceiro número: "))
d = float(input("Digite o quarto número: "))

media = (a + b + c + d)/4
if media > 1:
  print(f"a média",media,"é positiva")
else:
  print(f"a média",media,"é negativa")

#Escreva um programa que leia 20 valores inteiros e informe a média deles, o maior e o menor valor.
lista = []

for i in range(20):
  n = int(input("Insira o número: "))
  lista.append(n)

media = sum(lista)/20
print(f"A média da lista é",media)
print(f"O maior número da lista é",max(lista))
print(f"O menor número da lista é",min(lista))

#Crie uma função para desenhar uma linha, usando o caractere '_' (underline). O tamanho da linha deve
#ser definido na chamada da função.
def linha():
  for i in range(numero):
    print("_", end = "")

numero = int(input("Digite o tamanho da linha: "))
linha()

#Crie uma função que receba como parâmetro uma lista, com valores de qualquer tipo. A função deve
#imprimir todos os elementos da lista, enumerando-os.
lis = []
def numerar():
  for i in range(quantidade):
    print(lis[i], i + 1)

quantidade = int(input("Insira a quantidade de nomes a ser colocada: "))

for o in range(quantidade):
  n = str(input("Insira o nome: "))
  lis.append(n)

numerar()

#Crie um programa que converta horas em segundos, conforme o valor que o usuário informar quan-
#do solicitado a ele.
horas = int(input("Escreva as horas: "))

hora_min = horas*60

print(hora_min)

#Altere o código a seguir, para o menor número de linhas possível, mantendo o mesmo resultado:
#print(" *")
#print(" * *")
#print(" * *")
#print(" * *")
#print("*** ***")
#print(" * *")
#print(" * *")
#print(" *****")
linha = [" *"," * *"," * *"," * *","*** ***"," * *"," * *"," *****"]
for i in range(8):
  print(linha[i])